## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [ ]:
df = pd.read_excel("CSEB_Attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0%,Critical,36 more,Never,12
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0

#### Section 1: Data Inspection

In [4]:
#"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
print(df.head(10))
print(df.shape)
print(df.dtypes)

      Roll No           Student Name                                  Subject  \
0  4MW24CS061           KAVYA KAMATH  Data Science & GenAI - 3nd Yr - CSE - B
1  4MW24CS062              KEERTHANA  Data Science & GenAI - 3nd Yr - CSE - B
2  4MW24CS063       KEERTHI.R.SHETTY  Data Science & GenAI - 3nd Yr - CSE - B
3  4MW24CS064                 KHUSHI  Data Science & GenAI - 3nd Yr - CSE - B
4  4MW24CS065         KISHAN KUMAR K  Data Science & GenAI - 3nd Yr - CSE - B
5  4MW24CS066             KOUSHTUBHA  Data Science & GenAI - 3nd Yr - CSE - B
6  4MW24CS067                 KRITHI  Data Science & GenAI - 3nd Yr - CSE - B
7  4MW24CS068               KRITHIKA  Data Science & GenAI - 3nd Yr - CSE - B
8  4MW24CS069                LAKSHMI  Data Science & GenAI - 3nd Yr - CSE - B
9  4MW24CS070  LAVANYA SHANKAR MOGER  Data Science & GenAI - 3nd Yr - CSE - B

   Total Classes  Present  Absent  Excused Attendance %    Status  \
0             12       12       0        0         100%      Safe
1             12       12       0        0         100%      Safe
2             12       12       0        0         100%      Safe
3             12       11       1        0          92%      Safe
4             12       11       1        0          92%      Safe
5             12        1      11        0           8%  Critical
6             12       12       0        0         100%      Safe
7             12       12       0        0         100%      Safe
8             12       12       0        0         100%      Safe
9             12       10       2        0          83%   Warning

  Classes Needed (75%) Last Present Date  Consecutive Absences
0                ✓ Met        2026-10-09                     0
1                ✓ Met        2026-10-09                     0
2                ✓ Met        2026-10-09                     0
3                ✓ Met        2026-10-09                     0
4                ✓ Met        2026-10-09                     0
5              32 more        2026-09-18                     5
6                ✓ Met        2026-10-09                     0
7                ✓ Met        2026-10-09                     0
8                ✓ Met        2026-10-09                     0
9                ✓ Met        2026-10-09                     0
(65, 12)
Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [11]:
#"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
df['last_present_date'] = df['last_present_date'].replace('Never', pd.NA)

print(df.isnull().sum())

roll_no                  0
student_name             0
subject                  0
total_classes            0
present                  0
absent                   0
excused                  0
attendance_pct           0
status                   0
classes_needed_75_pct    0
last_present_date        2
consecutive_absences     0
dtype: int64

In [7]:
#"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
df.columns = [
    'roll_no',
    'student_name',
    'subject',
    'total_classes',
    'present',
    'absent',
    'excused',
    'attendance_pct',
    'status',
    'classes_needed_75_pct',
    'last_present_date',
    'consecutive_absences'
]

print(df.columns)

Index(['roll_no', 'student_name', 'subject', 'total_classes', 'present',
       'absent', 'excused', 'attendance_pct', 'status',
       'classes_needed_75_pct', 'last_present_date', 'consecutive_absences'],
      dtype='str')

In [12]:
#"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
df['attendance_pct'] = df['attendance_pct'].str.replace('%', '').astype(float)

df['attendance_pct'] = df['attendance_pct'] / 100

df['last_present_date'] = pd.to_datetime(
    df['last_present_date'].replace('Never', np.nan)
)

print(df)

       roll_no       student_name                                  subject  \
0   4MW24CS061       KAVYA KAMATH  Data Science & GenAI - 3nd Yr - CSE - B
1   4MW24CS062          KEERTHANA  Data Science & GenAI - 3nd Yr - CSE - B
2   4MW24CS063   KEERTHI.R.SHETTY  Data Science & GenAI - 3nd Yr - CSE - B
3   4MW24CS064             KHUSHI  Data Science & GenAI - 3nd Yr - CSE - B
4   4MW24CS065     KISHAN KUMAR K  Data Science & GenAI - 3nd Yr - CSE - B
..         ...                ...                                      ...
60  4MW24CS121           SAHANA M  Data Science & GenAI - 3nd Yr - CSE - B
61  4MW24CS122             SAKSHI  Data Science & GenAI - 3nd Yr - CSE - B
62  4MW25CS404  MANISH M BHANDARY  Data Science & GenAI - 3nd Yr - CSE - B
63  4MW25CS405    MANYA PRARTHANA  Data Science & GenAI - 3nd Yr - CSE - B
64  4MW25CS406              ROHAN  Data Science & GenAI - 3nd Yr - CSE - B

    total_classes  present  absent  excused  attendance_pct    status  \
0              12       12       0        0            1.00      Safe
1              12       12       0        0            1.00      Safe
2              12       12       0        0            1.00      Safe
3              12       11       1        0            0.92      Safe
4              12       11       1        0            0.92      Safe
..            ...      ...     ...      ...             ...       ...
60             12       10       2        0            0.83   Warning
61             12       11       1        0            0.92      Safe
62             12       11       1        0            0.92      Safe
63             12        0      12        0            0.00  Critical
64             12       10       2        0            0.83   Warning

   classes_needed_75_pct last_present_date  consecutive_absences
0                  ✓ Met        2026-10-09                     0
1                  ✓ Met        2026-10-09                     0
2                  ✓ Met        2026-10-09                     0
3                  ✓ Met        2026-10-09                     0
4                  ✓ Met        2026-10-09                     0
..                   ...               ...                   ...
60                 ✓ Met        2026-10-09                     0
61                 ✓ Met        2026-10-09                     0
62                 ✓ Met        2026-10-09                     0
63               36 more               NaT                    12
64                 ✓ Met        2026-10-09                     0

[65 rows x 12 columns]

#### Section 2: Filtering & Selection

In [13]:
#"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
result = df[df['status'] == 'Critical'].sort_values('attendance_pct')

print(result)

       roll_no     student_name                                  subject  \
10  4MW24CS071       LAXMEESH V  Data Science & GenAI - 3nd Yr - CSE - B
63  4MW25CS405  MANYA PRARTHANA  Data Science & GenAI - 3nd Yr - CSE - B
13  4MW24CS074   MAHALINGAPPA C  Data Science & GenAI - 3nd Yr - CSE - B
5   4MW24CS066       KOUSHTUBHA  Data Science & GenAI - 3nd Yr - CSE - B
49  4MW24CS110       PRATHWEESH  Data Science & GenAI - 3nd Yr - CSE - B
46  4MW24CS107  PRATHAM G KUMAR  Data Science & GenAI - 3nd Yr - CSE - B
35  4MW24CS096    NITHIL SHETTY  Data Science & GenAI - 3nd Yr - CSE - B
29  4MW24CS090      NIKHIL NAIK  Data Science & GenAI - 3nd Yr - CSE - B
51  4MW24CS112            RAHUL  Data Science & GenAI - 3nd Yr - CSE - B

    total_classes  present  absent  excused  attendance_pct    status  \
10             12        0      12        0            0.00  Critical
63             12        0      12        0            0.00  Critical
13             12        1      11        0            0.08  Critical
5              12        1      11        0            0.08  Critical
49             12        1      11        0            0.08  Critical
46             12        1      11        0            0.08  Critical
35             12        1      11        0            0.08  Critical
29             12        7       5        0            0.58  Critical
51             12        7       5        0            0.58  Critical

   classes_needed_75_pct last_present_date  consecutive_absences
10               36 more               NaT                    12
63               36 more               NaT                    12
13               32 more        2026-09-22                     4
5                32 more        2026-09-18                     5
49               32 more        2026-09-18                     5
46               32 more        2026-09-18                     5
35               32 more        2026-09-18                     5
29                8 more        2026-10-09                     0
51                8 more        2026-09-29                     2

In [30]:
print(df.columns.tolist())

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75_pct', 'last_present_date', 'consecutive_absences', 'attendance_category', 'attendance_range', 'base_name', 'attendance_flag']

In [31]:
#"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
print(df[df['present'] == 0][
    ['roll_no', 'student_name', 'consecutive_absences']
])

       roll_no     student_name  consecutive_absences
10  4MW24CS071       LAXMEESH V                    12
63  4MW25CS405  MANYA PRARTHANA                    12

In [15]:
#"""Q7. Using .loc and .iloc, display:
#(a) All "Safe" students using .loc
#(b) The first 15 rows and columns 2-6 using .iloc """
print(df.loc[df['status'] == 'Safe'])
print(df.iloc[:15, 1:6])

       roll_no                   student_name  \
0   4MW24CS061                   KAVYA KAMATH
1   4MW24CS062                      KEERTHANA
2   4MW24CS063               KEERTHI.R.SHETTY
3   4MW24CS064                         KHUSHI
4   4MW24CS065                 KISHAN KUMAR K
6   4MW24CS067                         KRITHI
7   4MW24CS068                       KRITHIKA
8   4MW24CS069                        LAKSHMI
11  4MW24CS072                      LIKHITA S
12  4MW24CS073                   LIPIKA NAYAK
14  4MW24CS075                 MANASA R KULAL
15  4MW24CS076                    MANOJ KUMAR
16  4MW24CS077                          MANYA
17  4MW24CS078                      MANYA B C
19  4MW24CS080                  MAYUR S KULAL
20  4MW24CS081                        MEGHANA
22  4MW24CS083  MOKSHA JEETENDRA MURUDESHWARA
23  4MW24CS084                   NANDAN NAYAK
24  4MW24CS085                      NARMADA S
26  4MW24CS087                    NAVYA NAYAK
27  4MW24CS088           NEHA(VIJAYA POOJARY)
31  4MW24CS092             NIRMITHA K NAGARAJ
32  4MW24CS093                          NISHA
34  4MW24CS095                      NISHMITHA
36  4MW24CS097                 PANCHAMI NAYAK
37  4MW24CS098            PANCHAMI V DEVADIGA
38  4MW24CS099                     POOJASHREE
39  4MW24CS100               POORVI SUNIL DEV
40  4MW24CS101                       POORVIKA
41  4MW24CS102                         PRAJNA
43  4MW24CS104                PRANATHI S KONI
45  4MW24CS106                     PRANAV P K
47  4MW24CS108              PRATHIKA P SHETTY
48  4MW24CS109            PRATHIKSHA P SHETTY
52  4MW24CS113            RAJIYA BEGAM SURKOD
54  4MW24CS115                          RAMYA
56  4MW24CS117                   ROHAN MENDON
57  4MW24CS118                           SAFA
58  4MW24CS119                SAGAR H POOJARY
59  4MW24CS120                         SAHANA
61  4MW24CS122                         SAKSHI
62  4MW25CS404              MANISH M BHANDARY

                                    subject  total_classes  present  absent  \
0   Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
1   Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
2   Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
3   Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
4   Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
6   Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
7   Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
8   Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
11  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
12  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
14  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
15  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
16  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
17  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
19  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
20  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
22  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
23  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
24  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
26  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
27  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
31  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
32  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
34  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
36  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
37  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
38  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
39  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
40  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
41  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
43  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
45  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
47  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
48  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
52  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
54  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
56  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
57  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
58  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
59  Data Science & GenAI - 3nd Yr - CSE - B             12       12       0
61  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1
62  Data Science & GenAI - 3nd Yr - CSE - B             12       11       1

    excused  attendance_pct status classes_needed_75_pct last_present_date  \
0         0            1.00   Safe                 ✓ Met        2026-10-09
1         0            1.00   Safe                 ✓ Met        2026-10-09
2         0            1.00   Safe                 ✓ Met        2026-10-09
3         0            0.92   Safe                 ✓ Met        2026-10-09
4         0            0.92   Safe                 ✓ Met        2026-10-09
6         0            1.00   Safe                 ✓ Met        2026-10-09
7         0            1.00   Safe                 ✓ Met        2026-10-09
8         0            1.00   Safe                 ✓ Met        2026-10-09
11        0            1.00   Safe                 ✓ Met        2026-10-09
12        0            0.92   Safe                 ✓ Met        2026-10-09
14        0            1.00   Safe                 ✓ Met        2026-10-09
15        0            0.92   Safe                 ✓ Met        2026-10-09
16        0            0.92   Safe                 ✓ Met        2026-10-09
17        0            1.00   Safe                 ✓ Met        2026-10-09
19        0            1.00   Safe                 ✓ Met        2026-10-09
20        0            1.00   Safe                 ✓ Met        2026-10-09
22        0            0.92   Safe                 ✓ Met        2026-10-09
23        0            1.00   Safe                 ✓ Met        2026-10-09
24        0            0.92   Safe                 ✓ Met        2026-10-09
26        0            1.00   Safe                 ✓ Met        2026-10-09
27        0            0.92   Safe                 ✓ Met        2026-10-09
31        0            1.00   Safe                 ✓ Met        2026-10-09
32        0            1.00   Safe                 ✓ Met        2026-10-09
34        0            1.00   Safe                 ✓ Met        2026-10-09
36        0            0.92   Safe                 ✓ Met        2026-10-09
37        0            0.92   Safe                 ✓ Met        2026-10-09
38        0            1.00   Safe                 ✓ Met        2026-10-09
39        0            1.00   Safe                 ✓ Met        2026-10-09
40        0            1.00   Safe                 ✓ Met        2026-10-09
41        0            1.00   Safe                 ✓ Met        2026-10-09
43        0            0.92   Safe                 ✓ Met        2026-10-09
45        0            0.92   Safe                 ✓ Met        2026-10-09
47        0            1.00   Safe                 ✓ Met        2026-10-09
48        0            1.00   Safe                 ✓ Met        2026-10-09
52        0            0.92   Safe                 ✓ Met        2026-10-09
54        0            1.00   Safe                 ✓ Met        2026-10-09
56        0            1.00   Safe                 ✓ Met        2026-10-09
57        0            1.00   Safe                 ✓ Met        2026-10-09
58        0            0.92   Safe                 ✓ Met        2026-10-09
59        0            1.00   Safe                 ✓ Met        2026-10-09
61        0            0.92   Safe                 ✓ Met        2026-10-09
62        0            0.92   Safe                 ✓ Met        2026-10-09

    consecutive_absences
0                      0
1                      0
2                      0
3                      0
4                      0
6                      0
7                      0
8                      0
11                     0
12                     0
14                     0
15                     0
16                     0
17                     0
19                     0
20                     0
22                     0
23                     0
24                     0
26                     0
27                     0
31                     0
32                     0
34                     0
36                     0
37                     0
38                     0
39                     0
40                     0
41                     0
43                     0
45                     0
47                     0
48                     0
52                     0
54                     0
56                     0
57                     0
58                     0
59                     0
61                     0
62                     0
             student_name                                  subject  \
0            KAVYA KAMATH  Data Science & GenAI - 3nd Yr - CSE - B
1               KEERTHANA  Data Science & GenAI - 3nd Yr - CSE - B
2        KEERTHI.R.SHETTY  Data Science & GenAI - 3nd Yr - CSE - B
3                  KHUSHI  Data Science & GenAI - 3nd Yr - CSE - B
4          KISHAN KUMAR K  Data Science & GenAI - 3nd Yr - CSE - B
5              KOUSHTUBHA  Data Science & GenAI - 3nd Yr - CSE - B
6                  KRITHI  Data Science & GenAI - 3nd Yr - CSE - B
7                KRITHIKA  Data Science & GenAI - 3nd Yr - CSE - B
8                 LAKSHMI  Data Science & GenAI - 3nd Yr - CSE - B
9   LAVANYA SHANKAR MOGER  Data Science & GenAI - 3nd Yr - CSE - B
10             LAXMEESH V  Data Science & GenAI - 3nd Yr - CSE - B
11              LIKHITA S  Data Science & GenAI - 3nd Yr - CSE - B
12           LIPIKA NAYAK  Data Science & GenAI - 3nd Yr - CSE - B
13         MAHALINGAPPA C  Data Science & GenAI - 3nd Yr - CSE - B
14         MANASA R KULAL  Data Science & GenAI - 3nd Yr - CSE - B

    total_classes  present  absent
0              12       12       0
1              12       12       0
2              12       12       0
3              12       11       1
4              12       11       1
5              12        1      11
6              12       12       0
7              12       12       0
8              12       12       0
9              12       10       2
10             12        0      12
11             12       12       0
12             12       11       1
13             12        1      11
14             12       12       0

In [16]:
#"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
result = df[df['consecutive_absences'] >= 5]

print(result[['student_name', 'status', 'last_present_date']])

       student_name    status last_present_date
5        KOUSHTUBHA  Critical        2026-09-18
10       LAXMEESH V  Critical               NaT
35    NITHIL SHETTY  Critical        2026-09-18
46  PRATHAM G KUMAR  Critical        2026-09-18
49       PRATHWEESH  Critical        2026-09-18
63  MANYA PRARTHANA  Critical               NaT

### Section 3: Grouping & Aggregation

In [18]:
#"""Q9. Group the data by Status and compute: 
#a) Count of students 
#b) Average attendance %  
#c) Maximum consecutive absences"""
result = df.groupby('status').agg({
    'student_name': 'count',
    'attendance_pct': 'mean',
    'consecutive_absences': 'max'
})

print(result)

          student_name  attendance_pct  consecutive_absences
status
Critical             9        0.173333                    12
Safe                42        0.969524                     0
Warning             14        0.807143                     1

In [17]:
#"""Q10. Create a new column Attendance Category:
#≥ 90% → "Excellent"
#75-89% → "Good"
#60-74% → "Average"
#< 60% → "Poor"
#Then use groupby() to count students in each category."""
df['attendance_category'] = pd.cut(
    df['attendance_pct'],
    bins=[0, 0.60, 0.75, 0.85, 1.0],
    labels=['Poor', 'Average', 'Good', 'Excellent']
)

print(df)

       roll_no       student_name                                  subject  \
0   4MW24CS061       KAVYA KAMATH  Data Science & GenAI - 3nd Yr - CSE - B
1   4MW24CS062          KEERTHANA  Data Science & GenAI - 3nd Yr - CSE - B
2   4MW24CS063   KEERTHI.R.SHETTY  Data Science & GenAI - 3nd Yr - CSE - B
3   4MW24CS064             KHUSHI  Data Science & GenAI - 3nd Yr - CSE - B
4   4MW24CS065     KISHAN KUMAR K  Data Science & GenAI - 3nd Yr - CSE - B
..         ...                ...                                      ...
60  4MW24CS121           SAHANA M  Data Science & GenAI - 3nd Yr - CSE - B
61  4MW24CS122             SAKSHI  Data Science & GenAI - 3nd Yr - CSE - B
62  4MW25CS404  MANISH M BHANDARY  Data Science & GenAI - 3nd Yr - CSE - B
63  4MW25CS405    MANYA PRARTHANA  Data Science & GenAI - 3nd Yr - CSE - B
64  4MW25CS406              ROHAN  Data Science & GenAI - 3nd Yr - CSE - B

    total_classes  present  absent  excused  attendance_pct    status  \
0              12       12       0        0            1.00      Safe
1              12       12       0        0            1.00      Safe
2              12       12       0        0            1.00      Safe
3              12       11       1        0            0.92      Safe
4              12       11       1        0            0.92      Safe
..            ...      ...     ...      ...             ...       ...
60             12       10       2        0            0.83   Warning
61             12       11       1        0            0.92      Safe
62             12       11       1        0            0.92      Safe
63             12        0      12        0            0.00  Critical
64             12       10       2        0            0.83   Warning

   classes_needed_75_pct last_present_date  consecutive_absences  \
0                  ✓ Met        2026-10-09                     0
1                  ✓ Met        2026-10-09                     0
2                  ✓ Met        2026-10-09                     0
3                  ✓ Met        2026-10-09                     0
4                  ✓ Met        2026-10-09                     0
..                   ...               ...                   ...
60                 ✓ Met        2026-10-09                     0
61                 ✓ Met        2026-10-09                     0
62                 ✓ Met        2026-10-09                     0
63               36 more               NaT                    12
64                 ✓ Met        2026-10-09                     0

   attendance_category
0            Excellent
1            Excellent
2            Excellent
3            Excellent
4            Excellent
..                 ...
60                Good
61           Excellent
62           Excellent
63                 NaN
64                Good

[65 rows x 13 columns]

In [32]:
#"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
print("Total Classes:", df['total_classes'].sum())
print("Total Present:", df['present'].sum())
print("Total Absent:", df['absent'].sum())

Total Classes: 780
Total Present: 643
Total Absent: 137

In [27]:
#"""Q12. Group by Status and use .agg() to find:
#a)min, max, and mean of Present
#b)sum of Absent"""
result = df.groupby('status').agg({
    'attendance_pct': ['min', 'max']
})

print(result)

         attendance_pct
                    min   max
status
Critical           0.00  0.58
Safe               0.92  1.00
Warning            0.75  0.83

### Section 4: Feature Engineering & Transformation

In [33]:
#"""Q13. Create a new column Risk Score using the formula:
#Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
#Display the top 10 students with the highest risk score."""
df['risk_score'] = (
    df['absent'] * 0.4 +
    df['consecutive_absences'] * 0.6
)

print(df.nlargest(10, 'risk_score'))

       roll_no     student_name                                  subject  \
10  4MW24CS071       LAXMEESH V  Data Science & GenAI - 3nd Yr - CSE - B
63  4MW25CS405  MANYA PRARTHANA  Data Science & GenAI - 3nd Yr - CSE - B
5   4MW24CS066       KOUSHTUBHA  Data Science & GenAI - 3nd Yr - CSE - B
35  4MW24CS096    NITHIL SHETTY  Data Science & GenAI - 3nd Yr - CSE - B
46  4MW24CS107  PRATHAM G KUMAR  Data Science & GenAI - 3nd Yr - CSE - B
49  4MW24CS110       PRATHWEESH  Data Science & GenAI - 3nd Yr - CSE - B
13  4MW24CS074   MAHALINGAPPA C  Data Science & GenAI - 3nd Yr - CSE - B
51  4MW24CS112            RAHUL  Data Science & GenAI - 3nd Yr - CSE - B
29  4MW24CS090      NIKHIL NAIK  Data Science & GenAI - 3nd Yr - CSE - B
33  4MW24CS094        NISHA M B  Data Science & GenAI - 3nd Yr - CSE - B

    total_classes  present  absent  excused  attendance_pct    status  \
10             12        0      12        0            0.00  Critical
63             12        0      12        0            0.00  Critical
5              12        1      11        0            0.08  Critical
35             12        1      11        0            0.08  Critical
46             12        1      11        0            0.08  Critical
49             12        1      11        0            0.08  Critical
13             12        1      11        0            0.08  Critical
51             12        7       5        0            0.58  Critical
29             12        7       5        0            0.58  Critical
33             12       10       2        0            0.83   Warning

   classes_needed_75_pct last_present_date  consecutive_absences  \
10               36 more               NaT                    12
63               36 more               NaT                    12
5                32 more        2026-09-18                     5
35               32 more        2026-09-18                     5
46               32 more        2026-09-18                     5
49               32 more        2026-09-18                     5
13               32 more        2026-09-22                     4
51                8 more        2026-09-29                     2
29                8 more        2026-10-09                     0
33                 ✓ Met        2026-10-06                     1

   attendance_category attendance_range     base_name attendance_flag  \
10                 NaN         Critical      LAXMEESH       Defaulter
63                 NaN         Critical         MANYA       Defaulter
5                 Poor         Critical    KOUSHTUBHA       Defaulter
35                Poor         Critical        NITHIL       Defaulter
46                Poor         Critical       PRATHAM       Defaulter
49                Poor         Critical    PRATHWEESH       Defaulter
13                Poor         Critical  MAHALINGAPPA       Defaulter
51                Poor         Critical         RAHUL       Defaulter
29                Poor         Critical        NIKHIL       Defaulter
33                Good         Critical         NISHA       Defaulter

    risk_score
10        12.0
63        12.0
5          7.4
35         7.4
46         7.4
49         7.4
13         6.8
51         3.2
29         2.0
33         1.4

In [34]:
#"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
df['classes_needed'] = pd.to_numeric(
    df['classes_needed_75_pct'].astype(str).str.extract(r'(\d+)')[0],
    errors='coerce'
).fillna(0).astype(int)

print(df[['student_name', 'classes_needed']])

         student_name  classes_needed
0        KAVYA KAMATH               0
1           KEERTHANA               0
2    KEERTHI.R.SHETTY               0
3              KHUSHI               0
4      KISHAN KUMAR K               0
..                ...             ...
60           SAHANA M               0
61             SAKSHI               0
62  MANISH M BHANDARY               0
63    MANYA PRARTHANA              36
64              ROHAN               0

[65 rows x 2 columns]

In [29]:
#"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
#a)"Defaulter" if attendance < 75%
#b)"Safe" otherwise """
df['attendance_flag'] = df['attendance_pct'].apply(
    lambda x: 'Defaulter' if x < 75 else 'Safe'
)

print(df[['student_name', 'attendance_flag']])

         student_name attendance_flag
0        KAVYA KAMATH       Defaulter
1           KEERTHANA       Defaulter
2    KEERTHI.R.SHETTY       Defaulter
3              KHUSHI       Defaulter
4      KISHAN KUMAR K       Defaulter
..                ...             ...
60           SAHANA M       Defaulter
61             SAKSHI       Defaulter
62  MANISH M BHANDARY       Defaulter
63    MANYA PRARTHANA       Defaulter
64              ROHAN       Defaulter

[65 rows x 2 columns]

In [28]:
#"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
df['attendance_range'] = pd.cut(
    df['attendance_pct'],
    bins=[0, 50, 75, 90, 100],
    labels=['Critical', 'Warning', 'Good', 'Excellent'],
    include_lowest=True
)

print(df[['student_name', 'attendance_range']])

         student_name attendance_range
0        KAVYA KAMATH         Critical
1           KEERTHANA         Critical
2    KEERTHI.R.SHETTY         Critical
3              KHUSHI         Critical
4      KISHAN KUMAR K         Critical
..                ...              ...
60           SAHANA M         Critical
61             SAKSHI         Critical
62  MANISH M BHANDARY         Critical
63    MANYA PRARTHANA         Critical
64              ROHAN         Critical

[65 rows x 2 columns]

### Section 5: Advanced Analysis

In [23]:
#"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
result = pd.pivot_table(
    df,
    index='status',
    columns='attendance_category',
    values='student_name',
    aggfunc='count',
    fill_value=0
)

print(result)

attendance_category  Poor  Average  Good  Excellent
status
Critical                7        0     0          0
Safe                    0        0     0         42
Warning                 0        4    10          0

In [24]:
#"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
df['base_name'] = df['student_name'].str.split().str[0]

duplicates = df[df.duplicated('base_name', keep=False)]

print(duplicates)

       roll_no         student_name                                  subject  \
16  4MW24CS077                MANYA  Data Science & GenAI - 3nd Yr - CSE - B
17  4MW24CS078            MANYA B C  Data Science & GenAI - 3nd Yr - CSE - B
25  4MW24CS086                NAVYA  Data Science & GenAI - 3nd Yr - CSE - B
26  4MW24CS087          NAVYA NAYAK  Data Science & GenAI - 3nd Yr - CSE - B
32  4MW24CS093                NISHA  Data Science & GenAI - 3nd Yr - CSE - B
33  4MW24CS094            NISHA M B  Data Science & GenAI - 3nd Yr - CSE - B
36  4MW24CS097       PANCHAMI NAYAK  Data Science & GenAI - 3nd Yr - CSE - B
37  4MW24CS098  PANCHAMI V DEVADIGA  Data Science & GenAI - 3nd Yr - CSE - B
44  4MW24CS105               PRANAV  Data Science & GenAI - 3nd Yr - CSE - B
45  4MW24CS106           PRANAV P K  Data Science & GenAI - 3nd Yr - CSE - B
56  4MW24CS117         ROHAN MENDON  Data Science & GenAI - 3nd Yr - CSE - B
59  4MW24CS120               SAHANA  Data Science & GenAI - 3nd Yr - CSE - B
60  4MW24CS121             SAHANA M  Data Science & GenAI - 3nd Yr - CSE - B
63  4MW25CS405      MANYA PRARTHANA  Data Science & GenAI - 3nd Yr - CSE - B
64  4MW25CS406                ROHAN  Data Science & GenAI - 3nd Yr - CSE - B

    total_classes  present  absent  excused  attendance_pct    status  \
16             12       11       1        0            0.92      Safe
17             12       12       0        0            1.00      Safe
25             12       10       2        0            0.83   Warning
26             12       12       0        0            1.00      Safe
32             12       12       0        0            1.00      Safe
33             12       10       2        0            0.83   Warning
36             12       11       1        0            0.92      Safe
37             12       11       1        0            0.92      Safe
44             12        9       3        0            0.75   Warning
45             12       11       1        0            0.92      Safe
56             12       12       0        0            1.00      Safe
59             12       12       0        0            1.00      Safe
60             12       10       2        0            0.83   Warning
63             12        0      12        0            0.00  Critical
64             12       10       2        0            0.83   Warning

   classes_needed_75_pct last_present_date  consecutive_absences  \
16                 ✓ Met        2026-10-09                     0
17                 ✓ Met        2026-10-09                     0
25                 ✓ Met        2026-10-09                     0
26                 ✓ Met        2026-10-09                     0
32                 ✓ Met        2026-10-09                     0
33                 ✓ Met        2026-10-06                     1
36                 ✓ Met        2026-10-09                     0
37                 ✓ Met        2026-10-09                     0
44                 ✓ Met        2026-10-09                     0
45                 ✓ Met        2026-10-09                     0
56                 ✓ Met        2026-10-09                     0
59                 ✓ Met        2026-10-09                     0
60                 ✓ Met        2026-10-09                     0
63               36 more               NaT                    12
64                 ✓ Met        2026-10-09                     0

   attendance_category attendance_range base_name
16           Excellent         Critical     MANYA
17           Excellent         Critical     MANYA
25                Good         Critical     NAVYA
26           Excellent         Critical     NAVYA
32           Excellent         Critical     NISHA
33                Good         Critical     NISHA
36           Excellent         Critical  PANCHAMI
37           Excellent         Critical  PANCHAMI
44             Average         Critical    PRANAV
45           Excellent         Critical    PRANAV
56           Excellent         Critical     ROHAN
59           Excellent         Critical    SAHANA
60                Good         Critical    SAHANA
63                 NaN         Critical     MANYA
64                Good         Critical     ROHAN

In [39]:
#""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
student_details = pd.DataFrame({
    'roll_no': df['roll_no'],
    'branch': ['CSE'] * len(df),
    'semester': [5] * len(df)
})

result = pd.merge(df, student_details, on='roll_no', how='inner')

print(result)

       roll_no       student_name                                  subject  \
0   4MW24CS061       KAVYA KAMATH  Data Science & GenAI - 3nd Yr - CSE - B
1   4MW24CS062          KEERTHANA  Data Science & GenAI - 3nd Yr - CSE - B
2   4MW24CS063   KEERTHI.R.SHETTY  Data Science & GenAI - 3nd Yr - CSE - B
3   4MW24CS064             KHUSHI  Data Science & GenAI - 3nd Yr - CSE - B
4   4MW24CS065     KISHAN KUMAR K  Data Science & GenAI - 3nd Yr - CSE - B
..         ...                ...                                      ...
60  4MW24CS121           SAHANA M  Data Science & GenAI - 3nd Yr - CSE - B
61  4MW24CS122             SAKSHI  Data Science & GenAI - 3nd Yr - CSE - B
62  4MW25CS404  MANISH M BHANDARY  Data Science & GenAI - 3nd Yr - CSE - B
63  4MW25CS405    MANYA PRARTHANA  Data Science & GenAI - 3nd Yr - CSE - B
64  4MW25CS406              ROHAN  Data Science & GenAI - 3nd Yr - CSE - B

    total_classes  present  absent  excused  attendance_pct    status  \
0              12       12       0        0            1.00      Safe
1              12       12       0        0            1.00      Safe
2              12       12       0        0            1.00      Safe
3              12       11       1        0            0.92      Safe
4              12       11       1        0            0.92      Safe
..            ...      ...     ...      ...             ...       ...
60             12       10       2        0            0.83   Warning
61             12       11       1        0            0.92      Safe
62             12       11       1        0            0.92      Safe
63             12        0      12        0            0.00  Critical
64             12       10       2        0            0.83   Warning

   classes_needed_75_pct last_present_date  consecutive_absences  \
0                  ✓ Met        2026-10-09                     0
1                  ✓ Met        2026-10-09                     0
2                  ✓ Met        2026-10-09                     0
3                  ✓ Met        2026-10-09                     0
4                  ✓ Met        2026-10-09                     0
..                   ...               ...                   ...
60                 ✓ Met        2026-10-09                     0
61                 ✓ Met        2026-10-09                     0
62                 ✓ Met        2026-10-09                     0
63               36 more               NaT                    12
64                 ✓ Met        2026-10-09                     0

   attendance_category attendance_range         base_name attendance_flag  \
0            Excellent         Critical             KAVYA       Defaulter
1            Excellent         Critical         KEERTHANA       Defaulter
2            Excellent         Critical  KEERTHI.R.SHETTY       Defaulter
3            Excellent         Critical            KHUSHI       Defaulter
4            Excellent         Critical            KISHAN       Defaulter
..                 ...              ...               ...             ...
60                Good         Critical            SAHANA       Defaulter
61           Excellent         Critical            SAKSHI       Defaulter
62           Excellent         Critical            MANISH       Defaulter
63                 NaN         Critical             MANYA       Defaulter
64                Good         Critical             ROHAN       Defaulter

    risk_score  classes_needed branch  semester
0          0.0               0    CSE         5
1          0.0               0    CSE         5
2          0.0               0    CSE         5
3          0.4               0    CSE         5
4          0.4               0    CSE         5
..         ...             ...    ...       ...
60         0.8               0    CSE         5
61         0.4               0    CSE         5
62         0.4               0    CSE         5
63        12.0              36    CSE         5
64         0.8               0    CSE         5

[65 rows x 20 columns]

In [38]:
#"""Q20. Export the following to separate CSV files:
#(a) All "Critical" students
#(b) Summary statistics grouped by Status
#(c) Top 10 students by Risk Score"""
df[df['status'] == 'Critical'].to_csv(
    'critical_students.csv', index=False
)
df.groupby('status').describe().to_csv('summary_statistics.csv')
df.nlargest(10, 'risk_score').to_csv(
    'top10_risk_students.csv', index=False
)
df

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,attendance_range,base_name,attendance_flag,risk_score,classes_needed
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,Critical,KAVYA,Defaulter,0.0,0
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,Critical,KEERTHANA,Defaulter,0.0,0
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,Critical,KEERTHI.R.SHETTY,Defaulter,0.0,0
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,Critical,KHUSHI,Defaulter,0.4,0
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,Critical,KISHAN,Defaulter,0.4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,Good,Critical,SAHANA,Defaulter,0.8,0
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,Critical,SAKSHI,Defaulter,0.4,0
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,Critical,MANISH,Defaulter,0.4,0
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,NaT,12,NaN,Critical,MANYA,Defaulter,12.0,36
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,Good,Critical,ROHAN,Defaulter,0.8,0